# Generated by Django 3.2.4 on 2021-08-15 15:03

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('uri_id', models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('code', 'Code')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('content', models.CharField(blank=True, max_length=4096)),
            ],
            bases=(api.models.AutoUriId, models.Model),
        ),
        migrations.CreateModel(
            name='GuideHowTo',
            fields=[
                ('uri_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('first', models.CharField(max_length=8)),
                ('first_ref', models.CharField(max_length=8)),
                ('steps', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('uri_id', models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(null=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
            bases=(api.models.AutoUriId, models.Model),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uri_id', models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            bases=(api.models.AutoUriId, models.Model),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('uri_id', models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
            bases=(api.models.AutoUriId, models.Model),
        ),
        migrations.CreateModel(
            name='SuperStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substep', to='api.step')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superstep', to='api.step')),
            ],
        ),
        migrations.CreateModel(
            name='StepModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('explanation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.explanation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.step')),
            ],
        ),
        migrations.CreateModel(
            name='HowToStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('how_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.howto')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.step')),
            ],
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('uri_id', models.CharField(max_length=8)),
                ('ref_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('howto_title', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('steps', models.JSONField()),
                ('first', models.CharField(max_length=8)),
                ('first_ref', models.CharField(max_length=8)),
                ('previous', models.CharField(blank=True, max_length=8)),
                ('previous_ref', models.CharField(blank=True, max_length=8)),
                ('next', models.CharField(blank=True, max_length=8)),
                ('next_ref', models.CharField(blank=True, max_length=8)),
                ('content', models.CharField(blank=True, max_length=4096)),
                ('howto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guidehowto')),
            ],
        ),
    ]
