# Generated by Django 3.2.4 on 2021-06-06 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name': "How To'",
            },
        ),
        migrations.CreateModel(
            name='HowToUriId',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uri_id', models.CharField(max_length=8)),
                ('how_to_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.howto')),
            ],
            options={
                'verbose_name': "How To Uri Id'",
            },
        ),
    ]
