# Generated by Django 3.2.4 on 2021-08-28 18:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidehowto',
            name='spaces',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('test', 'Test'), ('preview', 'Preview'), ('public', 'Public'), ('private', 'Private')], default='test', max_length=27),
            preserve_default=False,
        ),
    ]
