# Generated by Django 3.2.4 on 2021-07-17 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stepexplanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='step',
        ),
        migrations.AddField(
            model_name='explanation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explanation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
