# Generated by Django 3.2.4 on 2021-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guidehowto_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidehowto',
            name='howto_uri_id',
            field=models.CharField(default='00000000', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidehowto',
            name='uri_id',
            field=models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False),
        ),
    ]
