# Generated by Django 3.2.4 on 2021-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210828_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidehowto',
            name='spaces',
        ),
        migrations.AddField(
            model_name='guidehowto',
            name='space',
            field=models.CharField(choices=[('TST', 'Test'), ('PRV', 'Preview'), ('PBL', 'Public'), ('PRV', 'Private')], default='TST', max_length=3),
        ),
    ]
