# Generated by Django 3.2.4 on 2021-07-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210717_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='pos',
        ),
    ]
