# Generated by Django 3.2.4 on 2021-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='image',
            name='tooltip',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='image',
            name='uri_id',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
    ]
