# Generated by Django 3.2.4 on 2021-07-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210725_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tooltip',
            new_name='caption',
        ),
    ]
