# Generated by Django 3.2.4 on 2021-07-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexplanation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
        migrations.AlterField(
            model_name='stepexplanation',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.explanation'),
        ),
    ]
