# Generated by Django 3.2.4 on 2021-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210725_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('code', 'Code')], max_length=32),
        ),
    ]
