# Generated by Django 4.0.5 on 2022-07-02 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('text', 'Text'), ('code', 'Code')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('content', models.CharField(blank=True, max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('explanation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.explanation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='SequenceGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('space', models.CharField(choices=[('TST', 'test'), ('PRV', 'preview'), ('PBL', 'public'), ('PRV', 'private')], default='TST', max_length=3)),
                ('title', models.CharField(max_length=128)),
                ('first', models.UUIDField()),
            ],
            options={
                'db_table': 'sequence_guide',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('DECISION', 'Decision'), ('SEQUENCE', 'Sequence'), ('STEP', 'Step'), ('SUPER', 'Super')], default='STEP', max_length=13)),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='StepModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('pos', models.IntegerField()),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.step')),
            ],
            options={
                'db_table': 'step_module',
            },
        ),
        migrations.CreateModel(
            name='SequenceGuideStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sequence_title', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('decision_steps', models.CharField(blank=True, max_length=2048)),
                ('first', models.UUIDField()),
                ('previous', models.UUIDField(null=True)),
                ('next', models.UUIDField(null=True)),
                ('content', models.CharField(blank=True, max_length=4096)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sequenceguide')),
            ],
            options={
                'db_table': 'sequence_guide_step',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(null=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_decision', to='api.step')),
            ],
            options={
                'db_table': 'sequence',
            },
        ),
        migrations.CreateModel(
            name='LinkedStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('pos', models.IntegerField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_step_sub', to='api.step')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_step_super', to='api.step')),
            ],
            options={
                'db_table': 'linked_step',
            },
        ),
    ]
