# Generated by Django 4.0.3 on 2022-03-25 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('text', 'Text'), ('code', 'Code')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('content', models.CharField(blank=True, max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.explanation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(null=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'db_table': 'sequence',
            },
        ),
        migrations.CreateModel(
            name='SequenceGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('sequence_id', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('space', models.CharField(choices=[('TST', 'test'), ('PRV', 'preview'), ('PBL', 'public'), ('PRV', 'private')], default='TST', max_length=3)),
                ('title', models.CharField(max_length=128)),
                ('first', models.CharField(max_length=8)),
                ('first_ref', models.CharField(max_length=8)),
                ('steps', models.JSONField()),
            ],
            options={
                'db_table': 'sequence_guide',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='SuperStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.IntegerField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substep', to='api.step')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superstep', to='api.step')),
            ],
            options={
                'db_table': 'superstep',
            },
        ),
        migrations.CreateModel(
            name='StepModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.IntegerField()),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.step')),
            ],
            options={
                'db_table': 'step_module',
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.IntegerField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sequence')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.step')),
            ],
            options={
                'db_table': 'sequence_step',
            },
        ),
        migrations.CreateModel(
            name='SequenceGuideStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('ref_api_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sequence_title', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('steps', models.CharField(blank=True, max_length=2048)),
                ('decisions', models.CharField(blank=True, max_length=2048)),
                ('first', models.CharField(max_length=8)),
                ('first_ref', models.CharField(max_length=8)),
                ('previous', models.CharField(blank=True, max_length=8)),
                ('previous_ref', models.CharField(blank=True, max_length=8)),
                ('next', models.CharField(blank=True, max_length=8)),
                ('next_ref', models.CharField(blank=True, max_length=8)),
                ('content', models.CharField(blank=True, max_length=4096)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sequenceguide')),
            ],
            options={
                'db_table': 'sequence_guide_step',
            },
        ),
        migrations.CreateModel(
            name='DecisionStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.IntegerField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisionstep', to='api.step')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superdecision', to='api.step')),
            ],
            options={
                'db_table': 'decisionstep',
            },
        ),
    ]
