# Generated by Django 4.0.3 on 2022-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceguide',
            name='sequence_id',
        ),
        migrations.AlterField(
            model_name='sequenceguide',
            name='first',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='sequenceguide',
            name='first_ref',
            field=models.UUIDField(),
        ),
    ]
