# Generated by Django 4.0.3 on 2022-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sequenceguide_sequence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='first',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='first_ref',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='next',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='next_ref',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='previous',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='previous_ref',
            field=models.UUIDField(blank=True),
        ),
    ]
