# Generated by Django 4.0.3 on 2022-03-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sequenceguidestep_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequenceguidestep',
            old_name='decisions',
            new_name='decision_steps',
        ),
        migrations.RemoveField(
            model_name='sequenceguide',
            name='first_ref',
        ),
        migrations.RemoveField(
            model_name='sequenceguide',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='sequenceguidestep',
            name='first_ref',
        ),
        migrations.RemoveField(
            model_name='sequenceguidestep',
            name='next_ref',
        ),
        migrations.RemoveField(
            model_name='sequenceguidestep',
            name='previous_ref',
        ),
        migrations.RemoveField(
            model_name='sequenceguidestep',
            name='ref_api_id',
        ),
        migrations.RemoveField(
            model_name='sequenceguidestep',
            name='steps',
        ),
    ]
