# Generated by Django 4.0.6 on 2022-07-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_publish_date_sequence_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='uuid',
        ),
    ]
