# Generated by Django 4.0.6 on 2022-07-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sequence_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_sequence', to='api.step'),
        ),
    ]
