# Generated by Django 4.0.3 on 2022-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_decisions_sequenceguidestep_decision_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='next',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='sequenceguidestep',
            name='previous',
            field=models.UUIDField(null=True),
        ),
    ]
