# Generated by Django 3.2.9 on 2021-12-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_guidehowto_space'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuideHowTo',
            new_name='HowToGuide',
        ),
        migrations.RenameModel(
            old_name='GuideStep',
            new_name='HowToGuideStep',
        ),
        migrations.RemoveField(
            model_name='stepmodule',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='stepmodule',
            name='image',
        ),
        migrations.AlterModelTable(
            name='howto',
            table='howto',
        ),
        migrations.AlterModelTable(
            name='howtoguide',
            table='howto_guide',
        ),
        migrations.AlterModelTable(
            name='howtoguidestep',
            table='howto_guide_step',
        ),
        migrations.AlterModelTable(
            name='howtostep',
            table='howto_step',
        ),
        migrations.AlterModelTable(
            name='step',
            table='step',
        ),
        migrations.AlterModelTable(
            name='stepmodule',
            table='step_module',
        ),
        migrations.AlterModelTable(
            name='superstep',
            table='superstep',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.explanation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='DecisionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisionstep', to='api.step')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superdecision', to='api.step')),
            ],
            options={
                'db_table': 'decisionstep',
            },
        ),
        migrations.AddField(
            model_name='stepmodule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
    ]
