# Generated by Django 4.0.6 on 2022-07-13 19:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sequence_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('first', models.UUIDField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_published_sequence', to='api.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=128)),
                ('first', models.UUIDField()),
                ('previous', models.UUIDField(null=True)),
                ('next', models.UUIDField(null=True)),
                ('published_sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_step_published_sequence', to='api.publishedsequence')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_step_sequence', to='api.sequence')),
            ],
        ),
        migrations.RemoveField(
            model_name='sequenceguidestep',
            name='sequence',
        ),
        migrations.AlterModelTable(
            name='linkedstep',
            table=None,
        ),
        migrations.AlterModelTable(
            name='step',
            table=None,
        ),
        migrations.DeleteModel(
            name='SequenceGuide',
        ),
        migrations.DeleteModel(
            name='SequenceGuideStep',
        ),
    ]
